config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  resources :users
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  has_many :browsing_histories, dependent: :destroy
  belongs_to :user
end

app/models/browsing_history.rb
class BrowsingHistory < ApplicationRecord

  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :browsing_histories, dependent: :destroy
  has_many :articles, dependent: :destroy

  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    articles_path
  end

  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @user = User.find(current_user.id)
    @users = User.all.order(id: "ASC")
    @article = Article.new
    @articles = Article.all
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_to article_path(@article)
    else
      render :index
    end
  end

  def show
    @article = Article.find(params[:id])
    new_history = @article.browsing_histories.new
    new_history.user_id = current_user.id
    if current_user.browsing_histories.exists?(article_id: "#{params[:id]}")
      old_history = current_user.browsing_histories.find_by(article_id: "#{params[:id]}")
      old_history.destroy
    end
    histories_stock_limit = 10
    histories = current_user.browsing_histories.all
    if histories.count > histories_stock_limit
      histories[0].destroy
    end
    new_history.save
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to articles_path
    else
      render :edit
    end
  end

  def destroy
    article = Article.find(params[:id])
    if article.delete
      redirect_to articles_path
    else
      render :show
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :topic, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @histories = BrowsingHistory.where(user_id: params[:id])
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<h3>編集画面</h3>

<div class="post_form">
  <%= form_with model:@article, local:true do |f| %>
  <p>title</p>
  <%=  f.text_field :title %>
  <p>topic</p>
  <%= f.text_field :topic %>
  <%= f.submit %>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-2">
      <!--レフトサイドバー-->
      <nav class="sticky-top">
        <ul>
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users">User</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/articles">Articles</a>
          </li>
          <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to("logout", destroy_user_session_path,{method: :delete, class: "nav-link"}) %>
          <% end %>
        </ul>
      </nav>
      <div class="post_form ">
        <h3></h3>

      </div>
    </div>
    <div class=" col-7 mx-auto">
      <!--中央-->
      <div class="border border-secondary sticky-top bg-light"><h1>Home</h1></div>
      <div class="border border-secondary">
        <div class="p-2">
          <form><!--投稿用-->
          <%= form_with model:@article, local:true do |f| %>
          <div class="form-group">
            <label>title</label>
            <%=  f.text_field :title %>
          </div>
          <div class="form-group">
            <label>topic</label>
            <%= f.text_field :topic %>
          </div>
           <button type="submit" class="btn btn-primary">Submit</button>
          <% end %>
        </form>
       </div>
      </div>
      <% @articles.each do |article| %> <!--ariticleのインデックス-->
      <div class="article_index">
　      <div class="border border-secondary">
　         <div>
　           <%= link_to "/users/#{article.user.id}" do %>
　             <%= attachment_image_tag article.user, :profile_image, :fill, 40, 40, fallback: "no-user-image.png", size: "40x40" %>
　           <% end %>
　           <%= article.user.name%>
　         </div>
　        <div>title: <%= article.title %></div>
　        <div>topic: <%= article.topic %></div>
　      </div>
      </div>
      <% end %>
    </div>
    <div class="col-3">
      <!--右サイドバー-->
      <div class="sticky-top">
        <div class="what_happening">
        <h4>what_happening</h4>
        <ul class="list-group">
          <li class="list-group-item">オッズパークで年末を楽しも</li>
          <li class="list-group-item">千と千尋</li>
          <li class="list-group-item">村上春樹氏</li>
          <li class="list-group-item">Porta ac consectetur ac</li>
          <li class="list-group-item">Vestibulum at eros</li>
        </ul>
      </div>
      <div class="who_to_follow">
        <h4>Users New</h4>
        <ul class="list-group">
          <% @users.each do |user| %>
            <li class="list-group-item"><%= user.name %>さん</li>
          <% end %>
        </ul>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<h1>Articles</h1>

<table>
  <thead>
    <td></td>
    <td>title</td>
    <td>topic</td>
  </thead>
  <tbody>
    <td>
      <%= link_to "/users/#{@article.user_id}" do %>
        <%= @article.user.name %>
      <% end %>
    </td>
    <td><%= @article.title %></td>
    <td><%= @article.topic %></td>
    <td><%= link_to "edit", edit_article_path(@article) %></td>
    <td><%= link_to "destroy", article_path(@article), method: :delete %></td>
  </tbody>
</table>

app/views/homes/top.html.erb
<div class="container w-100">
  <div class="row w-100 center-block">
    <div class="mt-500 mx-auto">
    <div><h1>welcome</h1></div>
    </div>
    <div class="row button flex-column w-100 ">
    <%= link_to("Log in", new_user_session_path, {class: "btn btn-info btn-lg btn-block col-md-6 col-md-offset-6 mx-auto"}) %>
    <%= link_to("Sign Up", new_user_registration_path, {class: "btn btn-success btn-lg btn-block col-md-6 mx-auto"}) %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Article1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <div class="bg-info">
    <%= yield %>
  </div>

  </body>
</html>

app/views/users/edit.html.erb
user.edit

<h2>プロフィール編集</h2>
<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no-user-image.png",size: "50x50" %>
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/index.html.erb
Users
<table>
  <thead>
    <td>name</td>
  </thead>
  <% @users.each do |user| %>
  <tbody>
    <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no-user-image.png",size: "40x40" %></td>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= link_to "Show", user_path(user) %></td>
    <td><%= link_to "Edit", edit_user_path(user) %></td>
    <% end %>
  </tbody>
</table>


<%= link_to "Back", articles_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div >
  <h1><%= @user.name %>のページ</h1>
</div>

<div class="browsing_history">
  <p>閲覧した記事</p>
  <!--いまから実装-->
  <table>
  <thead>
    <td>title</td>
    <td>Time</td>
  </thead>
  <% @histories.each do |history| %>
  <tbody>
  </tbody>
  <% end %>
  </table>
</div>